import { z } from 'zod';

/** Every API error response has this shape. */
export const ApiErrorSchema = z.object({
  message: z.string(),
  code: z.string(),
  details: z.unknown().optional(),
});
export type ApiErrorBody = z.infer<typeof ApiErrorSchema>;

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_JSON: 'INVALID_JSON',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  GSTIN_TAKEN: 'GSTIN_TAKEN',
  INSURER_EXISTS: 'INSURER_EXISTS',
  CATALOG_ITEM_EXISTS: 'CATALOG_ITEM_EXISTS',
  IMPORT_FILE_INVALID: 'IMPORT_FILE_INVALID',
  PROPOSAL_LOCKED: 'PROPOSAL_LOCKED',
  DATA_SHEET_INCOMPLETE: 'DATA_SHEET_INCOMPLETE',
  MAIL_DISABLED: 'MAIL_DISABLED',
  RFQ_ATTACHMENT_TOO_LARGE: 'RFQ_ATTACHMENT_TOO_LARGE',
  QCR_INCOMPLETE: 'QCR_INCOMPLETE',
  RFQ_NOT_APPROVED: 'RFQ_NOT_APPROVED',
  QCR_CHANGED: 'QCR_CHANGED',
  QCR_NOT_APPROVED: 'QCR_NOT_APPROVED',
  TEMPLATE_VERSION_CONFLICT: 'TEMPLATE_VERSION_CONFLICT',
  SELF_UPDATE_NOT_ALLOWED: 'SELF_UPDATE_NOT_ALLOWED',
  RATE_LIMITED: 'RATE_LIMITED',
  MASTER_NOT_ACTIVE: 'MASTER_NOT_ACTIVE',
  MASTER_VERSION_NOT_DRAFT: 'MASTER_VERSION_NOT_DRAFT',
  OCCUPANCY_NOT_FOUND: 'OCCUPANCY_NOT_FOUND',
  PINCODE_NOT_FOUND: 'PINCODE_NOT_FOUND',
  MASTER_DATA_ERROR: 'MASTER_DATA_ERROR',
  UPSTREAM_UNAVAILABLE: 'UPSTREAM_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/** Same message for unknown user, inactive user, locked account and wrong password. */
export const INVALID_CREDENTIALS_MESSAGE = 'Email or password is incorrect.';
